name: iregexp
description: "A Dart library for I-Regexp: An Interoperable Regexp Format"
version: 0.1.2
repository: https://github.com/f3ath/iregexp

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  petitparser: ^6.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  check_coverage: ^0.0.4

cider:
  link_template:
    tag: https://github.com/f3ath/iregexp/releases/tag/%tag%
    diff: https://github.com/f3ath/iregexp/compare/%from%...%to%